---
Name: snapshot-extensions
After:
  - silverstripe/versioned
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Versioned\RecursivePublishable:
    class: SilverStripe\Snapshots\SnapshotPublishable
  SilverStripe\Versioned\Versioned:
    class: SilverStripe\Snapshots\SnapshotVersioned
SilverStripe\Versioned\ChangeSetItem:
  extensions:
    - SilverStripe\Snapshots\SnapshotChangeSetItem
SilverStripe\ORM\DataObject:
  extensions:
    - SilverStripe\Snapshots\SnapshotExtension
---
Only:
  moduleexists: 'silverstripe/cms'
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SilverStripe\Snapshots\SnapshotSiteTree

---
Name: snapshot-listeners
---
SilverStripe\CMS\Controllers\CMSMain:
  extensions:
    - SilverStripe\Snapshots\Listener\CMSMain\Listener

SilverStripe\Forms\GridField\GridField:
  extensions:
    - SilverStripe\Snapshots\Listener\GridField\Alteration\Listener
    - SilverStripe\Snapshots\Listener\GridField\Action\Listener

SilverStripe\Forms\FormRequestHandler:
  extensions:
    - SilverStripe\Snapshots\Listener\Form\Listener

SilverStripe\GraphQL\Scaffolding\Scaffolders\CRUD\Create:
  extensions:
    - SilverStripe\Snapshots\Listener\GraphQL\Mutation\Listener

SilverStripe\GraphQL\Scaffolding\Scaffolders\CRUD\Delete:
  extensions:
    - SilverStripe\Snapshots\Listener\GraphQL\Mutation\Listener

SilverStripe\GraphQL\Scaffolding\Scaffolders\CRUD\Update:
  extensions:
    - SilverStripe\Snapshots\Listener\GraphQL\Mutation\Listener

SilverStripe\GraphQL\Manager:
  extensions:
    - SilverStripe\Snapshots\Listener\GraphQL\Middleware\Listener

---
Name: snapshot-events
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Snapshots\Dispatch\Dispatcher:
    properties:
      handlers:
        formGeneric:
          on:
            'formSubmitted.unpublish': true
            'formSubmitted.doSave': true
            'formSubmitted.doDelete': true
          handler: %$SilverStripe\Snapshots\Handler\Form\Handler
        save:
          on:
            'formSubmitted.save': true
          handler: %$SilverStripe\Snapshots\Handler\Form\SaveHandler
        publish:
          on:
            'formSubmitted.publish': true
          handler: %$SilverStripe\Snapshots\Handler\Form\PublishHandler
        cmsMain:
          on:
            'cmsAction.savetreenode': true
          handler: %$SilverStripe\Snapshots\Handler\CMSMain\Handler
        gridFieldAction:
          on:
            'gridFieldAction.handleReorder': true
            'gridFieldAlteration.deleterecord': true
            'gridFieldAlteration.archiverecord': true
          handler: %$SilverStripe\Snapshots\Handler\GridField\Action\Handler
        graphqlMutation:
          on:
            'graphqlMutation.create': true
            'graphqlMutation.update': true
            'graphqlMutation.delete': true
          handler: %$SilverStripe\Snapshots\Handler\GraphQL\Mutation\Handler
