---
Name: snapshot-extensions
After:
  - silverstripe/versioned
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Versioned\RecursivePublishable:
    class: SilverStripe\Snapshots\SnapshotPublishable
  SilverStripe\Versioned\Versioned:
    class: SilverStripe\Snapshots\SnapshotVersioned
SilverStripe\Versioned\ChangeSetItem:
  extensions:
    - SilverStripe\Snapshots\SnapshotChangeSetItem
SilverStripe\ORM\DataObject:
  extensions:
    - SilverStripe\Snapshots\SnapshotExtension
---
Only:
  moduleexists: 'silverstripe/cms'
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SilverStripe\Snapshots\SnapshotSiteTree

---
Name: snapshot-listeners
---
SilverStripe\CMS\Controllers\CMSMain:
  extensions:
    - SilverStripe\Snapshots\Listener\Page\CMSMainAction

SilverStripe\Forms\GridField\GridField:
  extensions:
    - SilverStripe\Snapshots\Listener\GridField\AlterAction
    - SilverStripe\Snapshots\Listener\GridField\UrlHandlerAction

SilverStripe\Forms\FormRequestHandler:
  extensions:
    - SilverStripe\Snapshots\Listener\Form\Submission

SilverStripe\GraphQL\Scaffolding\Scaffolders\CRUD\Create:
  extensions:
    - SilverStripe\Snapshots\Listener\GraphQL\GenericAction

SilverStripe\GraphQL\Scaffolding\Scaffolders\CRUD\Delete:
  extensions:
    - SilverStripe\Snapshots\Listener\GraphQL\GenericAction

SilverStripe\GraphQL\Scaffolding\Scaffolders\CRUD\Update:
  extensions:
    - SilverStripe\Snapshots\Listener\GraphQL\GenericAction

SilverStripe\GraphQL\Manager:
  extensions:
    - SilverStripe\Snapshots\Listener\GraphQL\CustomAction

---
Name: snapshot-actions
---
SilverStripe\Core\Injector\Injector:
  # Form submission handlers
  SilverStripe\Snapshots\Handler\Form\FormSubmissionHandler.publish:
    class: SilverStripe\Snapshots\Handler\Form\FormSubmissionHandler
    constructor:
      message: 'Publish page'
      handlerName: 'publish'
  SilverStripe\Snapshots\Handler\Form\FormSubmissionHandler.unpublish:
    class: SilverStripe\Snapshots\Handler\Form\FormSubmissionHandler
    constructor:
      message: 'Unpublish page'
      handlerName: 'unpublish'
  SilverStripe\Snapshots\Handler\Form\FormSubmissionHandler.gridFieldSave:
    class: SilverStripe\Snapshots\Handler\Form\FormSubmissionHandler
    constructor:
      message: 'Save item'
      handlerName: 'doSave'
  SilverStripe\Snapshots\Handler\Form\FormSubmissionHandler.gridFieldDelete:
    class: SilverStripe\Snapshots\Handler\Form\FormSubmissionHandler
    constructor:
      message: 'Delete item'
      handlerName: 'doDelete'

  # CMS action handlers
  SilverStripe\Snapshots\Handler\CMSMain\ActionHandler.savetreenode:
    class: SilverStripe\Snapshots\Handler\CMSMain\ActionHandler
    constructor:
      action: 'savetreenode'
      message: 'Changed site tree position'

  # GridField action handlers
  SilverStripe\Snapshots\Handler\GridField\ActionHandler.deleterecord:
    class: SilverStripe\Snapshots\Handler\GridField\ActionHandler
    constructor:
      action: 'deleterecord'
      message: 'Delete item'

  # GridField manipulator handlers
  SilverStripe\Snapshots\Handler\GridField\AlterationHandler.handleReorder:
    class: SilverStripe\Snapshots\Handler\GridField\AlterationHandler
    constructor:
      action: 'handleReorder'
      message: 'Changed items order'

  # GraphQL mutation handlers
  SilverStripe\Snapshots\Handler\GraphQL\MutationHandler.create:
    class: SilverStripe\Snapshots\Handler\GraphQL\MutationHandler
    constructor:
      mutationType: 'create'
  SilverStripe\Snapshots\Handler\GraphQL\MutationHandler.update:
    class: SilverStripe\Snapshots\Handler\GraphQL\MutationHandler
    constructor:
      mutationType: 'update'
  SilverStripe\Snapshots\Handler\GraphQL\MutationHandler.delete:
    class: SilverStripe\Snapshots\Handler\GraphQL\MutationHandler
    constructor:
      mutationType: 'delete'


  SilverStripe\Snapshots\Dispatch\Dispatcher:
    properties:
      handlers:
        # Form submission handlers
        saveHandler:
          event: 'formSubmitted'
          handler: %$SilverStripe\Snapshots\Handler\Form\SaveHandler
        publishHandler:
          event: 'formSubmitted'
          handler: %$SilverStripe\Snapshots\Handler\Form\FormSubmissionHandler.publish
        unpublishHandler:
          event: 'formSubmitted'
          handler: %$SilverStripe\Snapshots\Handler\Form\FormSubmissionHandler.unpublish
        gridFieldSaveHandler:
          event: 'formSubmitted'
          handler: %$SilverStripe\Snapshots\Handler\Form\FormSubmissionHandler.gridFieldSave
        gridFieldDeleteHandler:
          event: 'formSubmitted'
          handler: %$SilverStripe\Snapshots\Handler\Form\FormSubmissionHandler.gridFieldDelete

        # CMSMain actions
        reorderSiteTreeHandler:
          event: 'cmsAction'
          handler: %$SilverStripe\Snapshots\Handler\CMSMain\ActionHandler.savetreenode

        # GridField URL providers
        deleteRecordHandler:
          event: 'gridFieldAction'
          handler: %$SilverStripe\Snapshots\Handler\GridField\ActionHandler.deleterecord

        # GridField action providers
        reorderHandler:
          event: 'gridFieldAlteration'
          handler: %$SilverStripe\Snapshots\Handler\GridField\AlterationHandler.handleReorder
        graphqlCreate:
          event: 'graphqlMutation'
          handler: %$SilverStripe\Snapshots\Handler\GraphQL\MutationHandler.create
        graphqlUpdate:
          event: 'graphqlMutation'
          handler: %$SilverStripe\Snapshots\Handler\GraphQL\MutationHandler.update
        graphqlDelete:
          event: 'graphqlMutation'
          handler: %$SilverStripe\Snapshots\Handler\GraphQL\MutationHandler.delete
