---
Name: snapshot-extensions
After:
  - silverstripe/versioned
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Versioned\RecursivePublishable:
    class: SilverStripe\Snapshots\SnapshotPublishable
  SilverStripe\Versioned\Versioned:
    class: SilverStripe\Snapshots\SnapshotVersioned
SilverStripe\Versioned\ChangeSetItem:
  extensions:
    - SilverStripe\Snapshots\SnapshotChangeSetItem
SilverStripe\ORM\DataObject:
  extensions:
    - SilverStripe\Snapshots\SnapshotExtension
---
Only:
  moduleexists: 'silverstripe/cms'
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SilverStripe\Snapshots\SnapshotSiteTree
---
Name: snapshot-events
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\EventDispatcher\Dispatch\Dispatcher:
    properties:
      handlers:
        formGeneric:
          on:
            'formSubmitted.unpublish': true
            'formSubmitted.doSave': true
            'formSubmitted.doDelete': true
          handler: %$SilverStripe\Snapshots\Handler\Form\Handler
        save:
          on:
            'formSubmitted.save': true
          handler: %$SilverStripe\Snapshots\Handler\Form\SaveHandler
        publish:
          on:
            'formSubmitted.publish': true
          handler: %$SilverStripe\Snapshots\Handler\Form\PublishHandler
        cmsMain:
          on:
            'cmsAction.savetreenode': true
          handler: %$SilverStripe\Snapshots\Handler\CMSMain\Handler
        gridFieldAction:
          on:
            'gridFieldAlteration.deleterecord': true
            'gridFieldAlteration.archiverecord': true
          handler: %$SilverStripe\Snapshots\Handler\GridField\Action\Handler
        gridFieldAlteration:
          on: []
          handler: %$SilverStripe\Snapshots\Handler\GridField\Alteration\Handler
        graphqlMutation:
          on:
            'graphqlMutation.create': true
            'graphqlMutation.update': true
            'graphqlMutation.delete': true
          handler: %$SilverStripe\Snapshots\Handler\GraphQL\Mutation\Handler
        graphqlMutation:
          on: []
          handler: %$SilverStripe\Snapshots\Handler\GraphQL\Middleware\Handler
