---
Name: snapshot-extensions
After:
  - silverstripe/versioned
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Versioned\RecursivePublishable:
    class: SilverStripe\Snapshots\SnapshotPublishable
  SilverStripe\Versioned\Versioned:
    class: SilverStripe\Snapshots\SnapshotVersioned
SilverStripe\Versioned\ChangeSetItem:
  extensions:
    - SilverStripe\Snapshots\SnapshotChangeSetItem
SilverStripe\ORM\DataObject:
  extensions:
    - SilverStripe\Snapshots\SnapshotExtension
---
Only:
  moduleexists: 'silverstripe/cms'
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SilverStripe\Snapshots\SnapshotSiteTree

---
Name: snapshot-listeners
---
SilverStripe\CMS\Controllers\CMSMain:
  extensions:
    - SilverStripe\Snapshots\Listener\CMSMain\CMSMainActionListener

SilverStripe\Forms\GridField\GridField:
  extensions:
    - SilverStripe\Snapshots\Listener\GridField\GridFieldAlterationListener
    - SilverStripe\Snapshots\Listener\GridField\GridFieldURLListener

SilverStripe\Forms\FormRequestHandler:
  extensions:
    - SilverStripe\Snapshots\Listener\Form\FormSubmissionListener

SilverStripe\GraphQL\Scaffolding\Scaffolders\CRUD\Create:
  extensions:
    - SilverStripe\Snapshots\Listener\GraphQL\GraphQLMutationListener

SilverStripe\GraphQL\Scaffolding\Scaffolders\CRUD\Delete:
  extensions:
    - SilverStripe\Snapshots\Listener\GraphQL\GraphQLMutationListener

SilverStripe\GraphQL\Scaffolding\Scaffolders\CRUD\Update:
  extensions:
    - SilverStripe\Snapshots\Listener\GraphQL\GraphQLMutationListener

SilverStripe\GraphQL\Manager:
  extensions:
    - SilverStripe\Snapshots\Listener\GraphQL\GraphQLMiddlewareListener

---
Name: snapshot-events
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Snapshots\Dispatch\Dispatcher:
    properties:
      handlers:
        -
          on: [ formSubmitted.unpublish, formSubmitted.doSave, formSubmitted.doDelete]
          handler: %$SilverStripe\Snapshots\Handler\Form\FormSubmissionHandler
        -
          on: [ formSubmitted.save ]
          handler: %$SilverStripe\Snapshots\Handler\Form\SaveHandler
        -
          on: [ formSubmitted.publish ]
          handler: %$SilverStripe\Snapshots\Handler\Form\PublishHandler
        -
          on: [ cmsAction.savetreenode ]
          handler: %$SilverStripe\Snapshots\Handler\CMSMain\ActionHandler
        -
          on: [ gridFieldAlteration.deleterecord, gridFieldAlteration.archiverecord ]
          handler: %$SilverStripe\Snapshots\Handler\GridField\URLActionHandler
        -
          on: [ gridFieldAction.handleReorder ]
          handler: %$SilverStripe\Snapshots\Handler\GridField\URLActionHandler
        -
          on: [ graphqlMutation.create, graphqlMutation.update, graphqlMutation.delete ]
          handler: %$SilverStripe\Snapshots\Handler\GraphQL\MutationHandler
